
FIND_PACKAGE(GLUT REQUIRED)

FIND_FILE( _FREEGLUT GL/freeglut.h HINTS /usr/include /usr/local/include)

MESSAGE(STATUS "freeglut: " ${_FREEGLUT})
IF(_FREEGLUT)
  SET(FREEGLUT_FOUND TRUE)
ELSE(_FREEGLUT)
  SET(FREEGLUT_FOUND FALSE)
ENDIF(_FREEGLUT)

MARK_AS_ADVANCED(FREEGLUT_FOUND)
